name: first-exercise-workflow
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Python Version
        run: python --version
      - name: Pip Version
        run: pip --version